"""Markdown report assembler.

Reads the files written by :mod:`ctd.pipeline` and produces a single
``REPORT.md`` that an HR person could skim and a stats person could
verify. Sections follow the natural flow of the analysis:

1. dataset summary
2. descriptive ICCs (motivating the multilevel approach)
3. OLS vs mixed coefficients (showing what the prototype got wrong)
4. headline mixed-model results
5. lag analysis (both directions)
6. cluster-bootstrap CIs
7. leave-one-out sensitivity
8. power analysis (if available)
9. figures
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

SECTION_ORDER: list[tuple[str, str]] = [
    ("Dataset", "intro"),
    ("Why multilevel: ICCs", "icc.txt"),
    ("Pooled vs within/between correlations", "within_between_correlations.txt"),
    ("Naive OLS vs mixed-effects coefficients", "ols_vs_mixed.txt"),
    ("Mixed model — stress", "mixed_stress.txt"),
    ("Mixed model — compulsions", "mixed_compulsion.txt"),
    ("Mixed model — stress × time × group interaction", "mixed_interaction.txt"),
    ("Lag: stress → compulsions", "lag_stress_to_compulsion.txt"),
    ("Lag: compulsions → stress (reverse-direction sanity check)", "lag_compulsion_to_stress.txt"),
    ("Cluster-bootstrap 95% CIs", "bootstrap_compulsion.txt"),
    ("Leave-one-participant-out sensitivity", "loo_compulsion.txt"),
    ("Simulation-based power grid", "power_grid.txt"),
]


def _table(path: Path) -> str:
    return f"```\n{path.read_text().rstrip()}\n```"


def _fig(label: str, path: Path, results_dir: Path) -> str:
    rel = path.relative_to(results_dir)
    return f"![{label}]({rel})"


def _dataset_blurb(data_path: Path) -> str:
    """Read the raw data file (if present) and report actual N × days × bins."""
    if not data_path.exists():
        return (
            "Simulated EMA dataset generated by "
            "`ctd.data.generate_synthetic_data_v2`. "
            "Re-run the pipeline to populate this section with the actual shape."
        )
    df = pd.read_csv(data_path)
    n = df["Participant"].nunique()
    days = df["Day"].nunique()
    bins = df["TimeBin"].nunique()
    return (
        f"{n} simulated participants × {days} days × {bins} time bins "
        f"({len(df)} observations), generated from "
        "`ctd.data.generate_synthetic_data_v2`. All slopes below are "
        "evaluated against this DGP — see the DAG above."
    )


def build_report(
    results_dir: Path | str = Path("results"),
    data_path: Path | str = Path("data/raw_data.csv"),
) -> Path:
    results_dir = Path(results_dir)
    data_path = Path(data_path)
    fig_dir = results_dir / "figures"

    lines: list[str] = []
    lines.append("# Reanalysis report\n")
    lines.append(
        "Auto-generated by `ctd run`. The narrative below walks through "
        "what the original prototype's OLS pipeline missed and how the "
        "mixed-effects reanalysis changes the picture.\n"
    )

    # 1. Data-generating DAG up front — readers can see the structure
    #    we're fitting against.
    dag = fig_dir / "dag.png"
    if dag.exists():
        lines.append("## Data-generating model\n")
        lines.append(_fig("DAG", dag, results_dir))
        lines.append(
            "Person-level latent traits (pink) feed into the observed "
            "outcomes (blue). Time-of-day (circadian) and lagged stress "
            "are exogenous drivers (yellow).\n"
        )

    # 2. Walk the section list.
    for title, source in SECTION_ORDER:
        if source == "intro":
            lines.append(f"## {title}\n")
            lines.append(_dataset_blurb(data_path) + "\n")
            continue
        path = results_dir / source
        if not path.exists():
            continue
        lines.append(f"## {title}\n")
        lines.append(_table(path))
        lines.append("")

    # 3. Figures section — everything in results/figures/.
    figs = [
        ("Circadian stress (per participant + pooled)", "circadian_stress.png"),
        ("Stress over time by compulsion group", "group_stress.png"),
        ("Stress vs outside time", "stress_vs_outside.png"),
        ("Compulsion-model coefficients (cluster bootstrap 95% CI)", "compulsion_forest.png"),
        ("Lag stress → compulsions", "lag_fwd.png"),
        ("Lag compulsions → stress", "lag_rev.png"),
        ("Power for the between-person effect", "power.png"),
    ]
    available = [(label, fig_dir / name) for label, name in figs if (fig_dir / name).exists()]
    if available:
        lines.append("## Figures\n")
        for label, path in available:
            lines.append(f"### {label}\n")
            lines.append(_fig(label, path, results_dir))
            lines.append("")

    out = results_dir / "REPORT.md"
    out.write_text("\n".join(lines).rstrip() + "\n")
    return out
